### ISSUE TITLE
Set manual completion only

### ISSUE THREAD

**Issue by matissel** [pfpayments/java-sdk#10]
Hey,

Context : I need to validate some transactions manually only (or set a big date before automatic approval), for each transactions of a certain product in PF checkout. Current issue is that if the "validator" is going in vacation, after x days, some transactions are automatically fullfilled. I already set `TransactionCompletionBehavior` to deferred when using `TransactionCreate`.

When setting `TransactionCompletionBehavior` to deferred, it seems to validate automatically transactions after a certain time. I'm not sure 100% but it looks like it depends on the payment method i.e. the connector (for example postfinance ecard with "Transaction Completion Timeout" set to x days). Is that accurate ? Does "Transaction completion timeout" is used to compute `Transaction.completionTimeoutOn` ? Does this also mean that when setting the behavior to deferred with this attribute, the transaction will be completed automatically (if no manual validation from us) and amount will be withdrawed from payer ? 

Edit : changed `authorizationTimeoutOn` with `completionTimeoutOn` since it's the completion we are dealing with

**Comment by theodorspringwallee** [comment]
Dear [matissel](https://github.com/matissel)

We will clarify this and will come back to you.

Best regards

**Comment by theodorspringwallee** [comment]
Dear [matissel](https://github.com/matissel)

Can you provide us some pfc transaction links, where your described behaviour was happening?

If you want to share this privately you also can contact the [PF Support](https://www.postfinance.ch/de/support/hotline.html) and reference to this git issue.

Thanks for your answer.

Best regards

**Comment by matissel** [comment]
Hello, 
Actually this is not an issue and we managed to deal with our situation. We changed each connector (visa, twint ...) to set the amount of days before automatic completion of the transaction. 
Thanks for the feedback,
Regards.

**Comment by theodorspringwallee** [comment]
Dear [matissel](https://github.com/matissel)

Great to hear, that you could solve your issue.

Best regards
