### ISSUE TITLE
Release 7.0.1 not available on maven central

### ISSUE THREAD

**Issue by dafo90** [pfpayments/java-sdk#12]
Dear @theodorspringwallee,

can you please publish version 7.0.1 on Maven Central?
Thank you

Best regards

**Comment by theodorspringwallee** [comment]
Dear [dafo90](https://github.com/dafo90)

It's available there: https://repo1.maven.org/maven2/ch/postfinance/postfinancecheckout-java-sdk/7.0.1/

Best regards
