### ISSUE TITLE
Share OpenAPI Specification

### ISSUE THREAD

**Issue by alex1989hu** [pfpayments/java-sdk#9]
Dear PostFinance Checkout Team,

I would like to generate the Java code by reading PostFinance Checkout API's OpenAPI specification.

The reason is simple, I would like to avoid using multiple HTTP libraries in one Java application.

By having the OpenAPI spec, all the consumers can control the libraries <https://openapi-generator.tech/docs/generators/java/>, including HTTP library.

As of now, the  PostFinance Checkout Java SDK uses `google-api-client` library:
https://github.com/pfpayments/java-sdk/blob/f68a8ac17bc9d9300121dd665ddf1926a1a07e6f/pom.xml#L314-L319

Please correct me if I am wrong, but I found some traces which suggest that `java-sdk` is generated by `openapi-generator` or similar tools (i.e. `swagger-codegen`): naming of the classes like RFC3339DateFormat, StringUtil, ApiClient.

Would it be possible to share the OAS2 / OAS3 file as well?

**Comment by theodorspringwallee** [comment]
Dear [alex1989hu](https://github.com/alex1989hu)

Our developer will check this.

Best regards

**Comment by theodorspringwallee** [comment]
Dear [alex1989hu](https://github.com/alex1989hu)

The OpenAPI specification is already public: https://checkout.postfinance.ch/api/swagger.json

Does this answer your request?

Best regards

**Comment by alex1989hu** [comment]
Dear @theodorspringwallee,

Thank you for sharing the `swagger.json`. Unfortunately, the specification is incomplete, specifically the authentication part is missing (<https://swagger.io/docs/specification/2-0/authentication/>).

If you generate code by using the `swagger.json` then you will not have any similar constructor of `ApiClient` what you have in your code:
https://github.com/pfpayments/java-sdk/blob/87b51efb23354b072afc3d757fc8426cf22f5197/src/main/java/ch/postfinance/sdk/ApiClient.java#L54-L77

The generated code does not utilize any authentication due to missing authentication part.

By the way, using `userId` and `applicationKey` is a must based on the current RequestInterceptor: https://github.com/pfpayments/java-sdk/blob/master/src/main/java/ch/postfinance/sdk/Auth.java#L60-L78

**Comment by theodorspringwallee** [comment]
Dear [alex1989hu](https://github.com/alex1989hu)

Here is the answer from our developers:
> We don’t generate the SDKs entirely starting from the OpenAPI specification. We have some templates that expect to have some static content. The constructors are part of this static content.
> We decided to release in this sprint a new constructor that will accept a proxy configuration, and we will release a new version.

Does this answer your question, respectively matches with your use case?

Best regards

**Comment by alex1989hu** [comment]
Dear @theodorspringwallee,

Thank for your answer. In this particular scenario, regrettably, the specification isn't particularly useful. As you mentioned, individual modifications are applied, and as a result, they are not accessible through the generated code.

Best regards

**Comment by dafo90** [comment]
> Dear [alex1989hu](https://github.com/alex1989hu)
> 
> Here is the answer from our developers:
> 
> > We don’t generate the SDKs entirely starting from the OpenAPI specification. We have some templates that expect to have some static content. The constructors are part of this static content.
> > We decided to release in this sprint a new constructor that will accept a proxy configuration, and we will release a new version.
> 
> Does this answer your question, respectively matches with your use case?
> 
> Best regards

Dear @theodorspringwallee, do you have a release date for the version with a new constructor that will accept a proxy configuration?

**Comment by theodorspringwallee** [comment]
Dear [dafo90](https://github.com/dafo90)

According to our developers, there should be a release on Monday for this.

Best regards

**Comment by dafo90** [comment]
> Dear [dafo90](https://github.com/dafo90)
> 
> According to our developers, there should be a release on Monday for this.
> 
> Best regards

Dear @theodorspringwallee

do you have any news about this release?

Thank you

Best regards

**Comment by theodorspringwallee** [comment]
Dear [dafo90](https://github.com/dafo90)

I'll clarify this.

Best regards

**Comment by theodorspringwallee** [comment]
Dear [dafo90](https://github.com/dafo90)

The release for the proxy extension is available now: https://github.com/pfpayments/java-sdk/releases

Best regards

**Comment by alex1989hu** [comment]
Dear @theodorspringwallee, I'm closing this issue because proxy support is not in the scope of the OpenAPI specification. I've created a new issue concerning proxy support here https://github.com/pfpayments/java-sdk/issues/11. Thank you for answers.

Best regards
